AutoWorkshop.Web/Controllers/BrandsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using AutoWorkshop.Web.Data;
using AutoWorkshop.Web.Data.Entities;
using AutoWorkshop.Web.Data.Repositories;
using Microsoft.AspNetCore.Authorization;

namespace AutoWorkshop.Web.Controllers
{
    [Authorize(Roles = "Admin")]
    public class BrandsController : Controller
    {
        public IBrandRepository _brandRepository { get; }

        public BrandsController(IBrandRepository brandRepository)
        {
            _brandRepository = brandRepository;
        }



        // GET: Brands
        public IActionResult Index()
        {
            return View(_brandRepository.GetAll());
        }



        // GET: Brands/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var brand = await _brandRepository.GetByIdAsync(id.Value);
            if (brand == null)
            {
                return NotFound();
            }

            return View(brand);
        }



        // GET: Brands/Create
        public IActionResult Create()
        {
            return View();
        }


        // POST: Brands/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Brand brand)
        {
            if (ModelState.IsValid)
            {
                await _brandRepository.CreateAsync(brand);
                return RedirectToAction(nameof(Index));
            }
            return View(brand);
        }



        // GET: Brands/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var brand = await _brandRepository.GetByIdAsync(id.Value);
            if (brand == null)
            {
                return NotFound();
            }
            return View(brand);
        }



        // POST: Brands/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Brand brand)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    await _brandRepository.UpdateAsync(brand);
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (! await _brandRepository.ExistAsync(brand.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(brand);
        }



        // GET: Brands/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var brand = await _brandRepository.GetByIdAsync(id.Value);
            if (brand == null)
            {
                return NotFound();
            }

            return View(brand);
        }



        // POST: Brands/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var brand = await _brandRepository.GetByIdAsync(id);
            await _brandRepository.DeleteAsync(brand);
            return RedirectToAction(nameof(Index));
        }
    }
}

AutoWorkshop.Web/Controllers/RepairsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using AutoWorkshop.Web.Data;
using AutoWorkshop.Web.Data.Entities;
using AutoWorkshop.Web.Data.Repositories;
using AutoWorkshop.Web.Models;
using AutoWorkshop.Web.Helpers;
using Microsoft.AspNetCore.Authorization;

namespace AutoWorkshop.Web.Controllers
{
    [Authorize(Roles ="Admin, Mechanic")]
    public class RepairsController : Controller
    {
        
        private readonly IRepairRepository _repairRepository;
        private readonly IClientRepository _clientRepository;
        private readonly IAppointmentRepository _appointmentRepository;
        private readonly IConverterHelper _converterHelper;
        private readonly IUserHelper _userHelper;

        public RepairsController(IRepairRepository repairRepository,
                                 IClientRepository clientRepository,
                                 IAppointmentRepository appointmentRepository,
                                 IConverterHelper converterHelper,
                                 IUserHelper userHelper)
        {
            
            _repairRepository = repairRepository;
            _clientRepository = clientRepository;
            _appointmentRepository = appointmentRepository;
            _converterHelper = converterHelper;
            _userHelper = userHelper;
        }


        // GET: Repairs
        public IActionResult Index()
        {
            var repair = _repairRepository.GetAll().Include(r => r.Appointment).ThenInclude(v => v.Vehicle).ThenInclude(b => b.Brand)
                                                   .Include(r => r.Appointment).ThenInclude(c => c.Client)
                                                   .Include(r => r.Appointment).ThenInclude(c => c.Mechanic)
                                                   .Include(r => r.Appointment).ThenInclude(c => c.AppointmentType).ToList();

            foreach (var rep in repair) //formatar a data
            {
                rep.FormatedDate = rep.CompletedAt.ToString("dd/MM/yyyy hh:mm");
            }
                                                   
            return View(repair);
        }


        // GET: Repairs/Create
        public IActionResult Create()
        {
            if (User.IsInRole("Mechanic"))
            {
                var model = new RepairViewModel
                {
                    Appointments = _appointmentRepository.GetComboUserAppointment(User.Identity.Name)
                };

                return View(model);
            }
            else
            {
                var model = new RepairViewModel
                {
                    Appointments = _appointmentRepository.GetComboAppointment()
                };

                return View(model);
            }
           
        }



        //POST: Repairs/Create
        //To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        //more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Repair repair)
        {
            if (ModelState.IsValid)
            {
                var client = _clientRepository.GetClientByUserEmail(User.Identity.Name);


                await _repairRepository.CreateAsync(repair);

                if (User.IsInRole("Mechanic"))
                {
                    return RedirectToAction("MyRepairs", "Mechanics");
                }
                return RedirectToAction(nameof(Index));
            }

            return View(repair);
        }

        //// GET: Repairs/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var repair = await _repairRepository.GetByIdWithAppointment(id.Value);
            if (repair == null)
            {
                return NotFound();
            }

            var vmodel = _converterHelper.ToRepairViewModel(repair);

            if (User.IsInRole("Mechanic"))
            {
                vmodel.Appointments = _appointmentRepository.GetComboUserAppointment(User.Identity.Name);
                vmodel.AppointmentId = repair.Appointment.Id;
            }
            else
            {
                vmodel.Appointments = _appointmentRepository.GetComboAppointment();
                vmodel.AppointmentId = repair.Appointment.Id;
            }

            return View(vmodel);
        }


        //// POST: Repairs/Edit/5
        //// To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        //// more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(RepairViewModel vmodel)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    var repair = _converterHelper.ToRepair(vmodel);
                    repair.AppointmentId = vmodel.AppointmentId;

                    await _repairRepository.UpdateAsync(repair);
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!await _repairRepository.ExistAsync(vmodel.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }

                if (User.IsInRole("Mechanic"))
                {
                    return RedirectToAction("MyRepairs", "Mechanics");
                }
                return RedirectToAction(nameof(Index));
            }

            return View(vmodel);
        }


        //// GET: Repairs/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var repair = await _repairRepository.GetByIdAsync(id.Value);
            if (repair == null)
            {
                return NotFound();
            }

            return View(repair);
        }


        //// POST: Repairs/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var repair = await _repairRepository.GetByIdAsync(id);
            await _repairRepository.DeleteAsync(repair);
            return RedirectToAction(nameof(Index));
        }

    }
}

AutoWorkshop.Web/Views/Admins/Create.cshtml
@model AutoWorkshop.Web.Data.Entities.Admin

@{
    ViewData["Title"] = "Create";
}

<h2>Create</h2>

<h4>Admin</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="FirstName" class="control-label"></label>
                <input asp-for="FirstName" class="form-control" />
                <span asp-validation-for="FirstName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LastName" class="control-label"></label>
                <input asp-for="LastName" class="form-control" />
                <span asp-validation-for="LastName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="StreetAddress" class="control-label"></label>
                <input asp-for="StreetAddress" class="form-control" />
                <span asp-validation-for="StreetAddress" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PhoneNumber" class="control-label"></label>
                <input asp-for="PhoneNumber" class="form-control" />
                <span asp-validation-for="PhoneNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PostalCode" class="control-label"></label>
                <input asp-for="PostalCode" class="form-control" />
                <span asp-validation-for="PostalCode" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DateofBirth" class="control-label"></label>
                <input asp-for="DateofBirth" class="form-control" />
                <span asp-validation-for="DateofBirth" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TaxIdentificationNumber" class="control-label"></label>
                <input asp-for="TaxIdentificationNumber" class="form-control" />
                <span asp-validation-for="TaxIdentificationNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CitizenCardNumber" class="control-label"></label>
                <input asp-for="CitizenCardNumber" class="form-control" />
                <span asp-validation-for="CitizenCardNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

AutoWorkshop.Web/Views/Admins/Delete.cshtml
@model AutoWorkshop.Web.Data.Entities.Admin

@{
    ViewData["Title"] = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Admin</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.FirstName)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.FirstName)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.LastName)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.LastName)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.StreetAddress)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.StreetAddress)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.PhoneNumber)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.PhoneNumber)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.PostalCode)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.PostalCode)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.DateofBirth)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.DateofBirth)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.TaxIdentificationNumber)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.TaxIdentificationNumber)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.CitizenCardNumber)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.CitizenCardNumber)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-default" /> |
        <a asp-action="ssIndex">Back to List</a>
    </form>
</div>

AutoWorkshop.Web/Views/Admins/Details.cshtml
@model AutoWorkshop.Web.Data.Entities.Admin

@{
    ViewData["Title"] = "Details";
}

<h2>Details</h2>

<div>
    <h4>Admin</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.FirstName)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.FirstName)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.LastName)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.LastName)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.StreetAddress)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.StreetAddress)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.PhoneNumber)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.PhoneNumber)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.PostalCode)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.PostalCode)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.DateofBirth)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.DateofBirth)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.TaxIdentificationNumber)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.TaxIdentificationNumber)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.CitizenCardNumber)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.CitizenCardNumber)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

AutoWorkshop.Web/Views/Admins/Edit.cshtml
@model AutoWorkshop.Web.Models.PersonEditViewModel

@{ ViewData["Title"] = "Edit"; }

<h2>Edit</h2>

<div class="text-success">
    @ViewBag.UserMessage
</div>

<br />
<h2 style=" margin-bottom:10px; border-bottom: solid 2px orange">Settings</h2>

<div class="container-fluid">
    <form method="post" enctype="multipart/form-data">
        <div asp-validation-summary="ModelOnly"></div>
        <input type="hidden" asp-for="Id" />
        <input type="hidden" asp-for="ImageUrl" />
         <input type="hidden" asp-for="UserId" />              

        <div class="row">
            <div class="col-md-3">

                <div class="d-flex justify-content-center" style="border: 1.5px solid gray; border-radius: 25px; margin-top: 10px">
                    @if (!string.IsNullOrEmpty(@Model.ImageUrl))
                    {
                         <img src="@Url.Content(@Model.ImageUrl)" alt="Image" style="border-radius:25px; max-width: 100%; height: 220px;" />
                    }
                </div>

                <div class="form-group" style="margin-top: 10px">
                    <label asp-for="ImageFile" class="control-label"></label>
                    <input asp-for="ImageFile" class="form-control" type="file" />
                    <span asp-validation-for="ImageFile" class="text-danger"></span>
                </div>

            </div>



            <div class="col-md-5">
                <h2 style="margin-bottom:2px; border-bottom: solid 2px gray">Personal Information</h2>

                <br />

                <div class="form-group">
                    <label asp-for="FirstName">First Name</label>
                    <input asp-for="FirstName" class="form-control" />
                    <span asp-validation-for="FirstName" class="text-warning"></span>
                </div>

                <div class="form-group">
                    <label asp-for="LastName">Last Name</label>
                    <input asp-for="LastName" class="form-control" />
                    <span asp-validation-for="LastName" class="text-warning"></span>
                </div>

                <div class="form-group">
                    <label asp-for="DateofBirth">Date of Birth Number</label>
                    <input asp-for="DateofBirth" class="form-control" />
                    <span asp-validation-for="DateofBirth" class="text-warning"></span>
                </div>

            </div>
            <div class="col-md-1 d-flex justify-content-md-center">
                <div class="align-self-end" style="height:300px;width: 2px; border: 1px gray solid; padding-top: 20px">

                </div>
            </div>
            <div class="col-md-3" style="margin-left: auto">

                <div class="form-group" style="">
                    <input type="submit" value="Update" class="btn btn-primary" />
                    <a asp-action="ChangePassword" class="btn btn-success">Change Password</a>
                </div>

                <br />

                <div class="form-group">
                    <label asp-for="PhoneNumber">Phone Number</label>
                    <input asp-for="PhoneNumber" class="form-control" />
                    <span asp-validation-for="PhoneNumber" class="text-warning"></span>
                </div>

                <div class="form-group">
                    <label asp-for="TaxIdentificationNumber">Tax Identification Number</label>
                    <input asp-for="TaxIdentificationNumber" class="form-control" />
                    <span asp-validation-for="TaxIdentificationNumber" class="text-warning"></span>
                </div>

                <div class="form-group">
                    <label asp-for="CitizenCardNumber">Citizen Card Number</label>
                    <input asp-for="CitizenCardNumber" class="form-control" />
                    <span asp-validation-for="CitizenCardNumber" class="text-warning"></span>
                </div>
            </div>

            <div class="col-8">
                <div class="form-group">
                    <label asp-for="StreetAddress">Street Address</label>
                    <input asp-for="StreetAddress" class="form-control" />
                    <span asp-validation-for="StreetAddress" class="text-warning"></span>
                </div>
            </div>

            <div class="col-1 d-flex justify-content-center" style="padding-top:15px">
                <div class="align-self-center" style="border: gray 1px solid; width: 50px; ">

                </div>
            </div>

            <div class="col-3">
                <div class="form-group">
                    <label asp-for="PostalCode">Postal Code</label>
                    <input asp-for="PostalCode" class="form-control" />
                    <span asp-validation-for="PostalCode" class="text-warning"></span>
                </div>
            </div>


        </div>

    </form>
</div>


@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

AutoWorkshop.Web/Views/Admins/Index.cshtml
@model AutoWorkshop.Web.Models.AdminIndexViewModel

@{
    ViewData["Title"] = "Index";
}

<br />


<h2><i class="fa fa-users 3x"></i> Registered Accounts</h2>

<div class="container-fluid">
    <div class="row">
        <div class="col-md-3" >
            <a class="nav-link text-dark font-weight-bold" style="font-size:large" asp-action="ssIndex" asp-controller="Clients">Clients:</a>
            <p class="d-flex justify-content-center" style="font-size:x-large">@Model.AllCount[0]</p>
        </div>

        <div class="col-md-3" >
            <a class="nav-link text-dark font-weight-bold" style="font-size:large" asp-action="ssIndex" asp-controller="Secretaries">Secretaries:</a>
            <p class="d-flex justify-content-center" style="font-size:x-large">@Model.AllCount[1]</p>
        </div>

        <div class="col-md-3" >
            <a class="nav-link text-dark font-weight-bold" style="font-size:large" asp-action="ssIndex" asp-controller="Mechanics">Mechanics:</a>
            <p class="d-flex justify-content-center" style="font-size:x-large">@Model.AllCount[2]</p>
        </div>

        <div class="col-md-3" >
            <a class="nav-link text-dark font-weight-bold" style="font-size:large" asp-action="ssIndex">Admins</a>
            <p class="d-flex justify-content-center" style="font-size:x-large">@Model.AllCount[3]</p>
        </div>
    </div>
</div>
<br />
<a type="button" class="btn btn-dark btn-block" style="padding:3px"  asp-action="CreateWithRole" asp-controller="Account">Create New Account </a> 

<br />
<br />
<br />

<div class="container-fluid">
    <div class="row font-weight-bolder" style="font-size:large">

        <div class="col-md-6 d-flex align-items-center" >
            <div><i class="fas fa-car fa-3x"></i></div>
            <a class="nav-link text-dark d-inline-block" asp-action="Index" asp-controller="Vehicles">Vehicles:</a>
            <a class="nav link d-inline-block">@Model.AllCount[4]</a>
        </div>

        <div class="col-md-6 d-flex align-items-center" >
            <a class="nav-link text-dark d-inline-block" asp-action="Index" asp-controller="Brands">Vehicle Brands:</a>
            <p class="nav link d-inline-block">@Model.AllCount[5]</p>
        </div>

    </div>
</div>
<br />
<div class="container-fluid">
    <div class="row font-weight-bolder" style="font-size:large">
        <div class="col-md-6 d-flex align-items-center">
            <div><i class="fa fa-calendar-check fa-3x"></i></div>
            <a class="nav-link text-dark d-inline-block" asp-action="Create" asp-controller="Appointments">Appointments:</a>
            <p class="nav link d-inline-block">@Model.AllCount[6]</p>
        </div>

        <div class="col-md-6 d-flex align-items-center" >
            <a class="nav-link text-dark d-inline-block" asp-action="Index" asp-controller="AppointmentTypes">Appointment Types:</a>
            <p class="nav link d-inline-block">@Model.AllCount[7]</p>
        </div>
    </div>
</div>
<br />
<div class="container-fluid">
    <div class="row font-weight-bolder" style="font-size:large">
        <div class="col-md-6 d-flex align-items-center" >
            <div><i class="fa fa-wrench fa-3x "></i></div>
            <a class="nav-link text-dark d-inline-block" asp-action="Index" asp-controller="Repairs">Repairs:</a>
            <p class="nav link d-inline-block">@Model.AllCount[8]</p>
        </div>

        <div class="col-md-6 d-flex align-items-center" >
            <a class="nav-link text-dark d-inline-block" asp-action="Index" asp-controller="Specialties">Mechanic's Specialties:</a>
            <p class="nav link d-inline-block">@Model.AllCount[9]</p>
        </div>
    </div>
</div>

AutoWorkshop.Web/Views/Admins/_AdminDetailsPartial.cshtml
@model AutoWorkshop.Web.Models.PersonEditViewModel




<div class="modal fade" id="vehicleModal">
    <div class="modal-dialog modal-lg modal-dialog-centered">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title float-left">Details</h4>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            </div>
            <div class="modal-body">
                <div style="background-color:darkorange; display: block; height: 6px;margin-bottom: 10px;"></div>
                <div class="container">
                    <div class="row" style="font-size: 16px">
                        <div class="col-3">
                            <div class="d-flex justify-content-center" style="border: 1.5px solid gray; border-radius: 25px;">
                                @if (!string.IsNullOrEmpty(@Model.ImageUrl))
                                {
                                    <img src="@Url.Content(@Model.ImageUrl)" alt="Image" style="border-radius:25px; max-width: 100%; height: 120px;" />
                                }
                            </div>
                        </div>

                        <div id="mtop" class="col-2 font-weight-bold text-dark">
                            <p><span>First Name </span></p>
                            <p><span>Last Name </span></p>
                            <p><span>Birthday </span></p>
                        </div>

                        <div id="mtop" class="col-2">
                            <p>@Model.FirstName</p>
                            <p>@Model.LastName</p>
                            <p>@Model.DateofBirth.ToShortDateString()</p>
                        </div>

                        <div id="mtop" class="col-3 font-weight-bold text-dark" style="padding-left: 20px">
                            <p><span>Phone Number </span></p>
                            <p><span>Tax Number </span></p>
                            <p><span>Citizen Card </span></p>
                        </div>

                        <div id="mtop" class="col-2">
                            <p>@Model.PhoneNumber</p>
                            <p>@Model.TaxIdentificationNumber</p>
                            <p>@Model.CitizenCardNumber</p>
                        </div>

                        <div id="mtop" class="col-2 font-weight-bold">
                            <p><span class="text-dark">Address</span></p>
                        </div>

                        <div id="mtop" class="col-5">
                            <p>@Model.StreetAddress</p>
                        </div>

                        <div id="mtop" class="col-3 font-weight-bold" style="padding-left: 20px">
                            <p><span class="text-dark">Postal Code</span></p>
                        </div>

                        <div id="mtop" class="col-2">
                            <p>@Model.PostalCode</p>
                        </div>
                    </div>
                </div>
            </div>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div><!-- /.modal -->