AutoWorkshop.Web/Models/VehicleViewModel.cs
using AutoWorkshop.Web.Data.Entities;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace AutoWorkshop.Web.Models
{
    public class VehicleViewModel
    {
        public int Id { get; set; }


        public int BrandId { get; set; }


        public Brand Brand { get; set; }



        [Required(ErrorMessage = "You must insert a value for {0}")]
        [StringLength(150, ErrorMessage = "{0} should be {2} to {1} characters long", MinimumLength = 2)]
        public string Model { get; set; }

        //public string SubModel { get; set; }

        [StringLength(150, ErrorMessage = "{0} should be {2} to {1} characters long", MinimumLength = 2)]
        [Required(ErrorMessage = "You must insert a value for {0}")]
        public string Transmission { get; set; } //automática ou manual


        [StringLength(150, ErrorMessage = "{0} should be {2} to {1} characters long", MinimumLength = 2)]
        [Required(ErrorMessage = "You must insert a value for {0}")]
        public string Type { get; set; }   //ligeiro ou pesado


        [Required(ErrorMessage = "You must insert a value for {0}")]
        [StringLength(50, ErrorMessage = "{0} should be {2} to {1} characters long", MinimumLength = 3)]
        public string Color { get; set; }


        [Range(2,10000000, ErrorMessage = "{0} should be {1} to 8 characters long")]
        [Required(ErrorMessage = "You must insert a value for {0}")]
        public int? Mileage { get; set; }


        [Range(2, 9999, ErrorMessage = "{0} should be {1} to 4 characters long")]
        [Required(ErrorMessage = "You must insert a value for {0}")]
        [Display(Name = "Engine Power")]
        public int? EnginePower { get; set; }


        [StringLength(8, ErrorMessage = "A {0} deverá ter entre {2} e {1} caracteres", MinimumLength = 8)]
        [Display(Name = "License Plate")]
        [Required(ErrorMessage = "You must insert a {0}")]
        public string LicensePlate { get; set; }



        [Required(ErrorMessage = "You must insert a {0} date")]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}", ApplyFormatInEditMode = false)]
        [Display(Name = "Last Maintenance")]
        public DateTime? LastMaintenance { get; set; }


        //public VIN_Number { get; set; }  //número que vem quando se monta o carro(para saber que é legit)


        public int ClientId { get; set; }

        public Client Client { get; set; }


        public IEnumerable<SelectListItem> Brands { get; set; }

        public IEnumerable<SelectListItem> Clients { get; set; }
    }
}

AutoWorkshop.Web/Controllers/VehiclesController.cs
using AutoWorkshop.Web.Data;
using AutoWorkshop.Web.Data.Repositories;
using AutoWorkshop.Web.Helpers;
using AutoWorkshop.Web.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Threading.Tasks;

namespace AutoWorkshop.Web.Controllers
{
    [Authorize(Roles ="Admin, Client")]
    public class VehiclesController : Controller
    {
        private readonly IVehicleRepository _vehicleRepository;
        private readonly IBrandRepository _brandRepository;
        private readonly IConverterHelper _converterHelper;
        private readonly IUserHelper _userHelper;
        private readonly IClientRepository _clientRepository;

        public VehiclesController(IVehicleRepository vehicleRepository,
                                  IBrandRepository brandRepository,
                                  IConverterHelper converterHelper,
                                  IUserHelper userHelper,
                                  IClientRepository clientRepository)
        {
            _vehicleRepository = vehicleRepository;
            _brandRepository = brandRepository;
            _converterHelper = converterHelper;
            _userHelper = userHelper;
            _clientRepository = clientRepository;
        }





        // GET: Vehicles
        public IActionResult Index()
        {

            var vehicles = _vehicleRepository.GetAll().Include(v => v.Brand).Include(u => u.Client);

            return View(vehicles);

        }


        public async Task<IActionResult> GetVehicles(int Id)
        {
            var vehicle = await _brandRepository.GetByIdWithBrand(Id);

            return PartialView("_VehiclesPartial", vehicle);
        }



        // GET: Vehicles/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var vehicle = await _vehicleRepository.GetByIdAsync(id.Value);
            vehicle.Brand = await _brandRepository.GetByIdAsync(vehicle.BrandId);
            if (vehicle == null)
            {
                return NotFound();
            }

            return View(vehicle);
        }



        // GET: Vehicles/Create
        public IActionResult Create()
        {
            if (User.IsInRole("Client"))
            {
                var vmodel = new VehicleViewModel
                {
                    Brands = _brandRepository.GetComboBrands()
                };

                return View(vmodel);
            }
            else
            {
                var vmodel = new VehicleViewModel
                {
                    Brands = _brandRepository.GetComboBrands(),
                    Clients = _clientRepository.GetComboClients()
                };

                return View(vmodel);
            }
        }


        // POST: Vehicles/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(VehicleViewModel vmodel)
        {
            if (this.ModelState.IsValid)
            {
                if (User.IsInRole("Client"))
                {
                    var path = string.Empty;
                    var client = _clientRepository.GetClientByUserEmail(User.Identity.Name);

                    var vehicle = _converterHelper.ToVehicle(vmodel, path, true);
                    vehicle.ClientId = client.Id;

                    await _vehicleRepository.CreateAsync(vehicle);

                    return RedirectToAction("MyVehicles", "Clients");
                }
                else
                {
                    var path = string.Empty;
                    var cli = await _clientRepository.GetByIdAsync(vmodel.ClientId);

                    var vehicle = _converterHelper.ToVehicle(vmodel, path, true);
                    vehicle.ClientId = cli.Id;

                    await _vehicleRepository.CreateAsync(vehicle);

                    return RedirectToAction(nameof(Index));
                }

            }
            return View(vmodel);
        }


        // GET: Vehicles/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var vehicle = await _brandRepository.GetByIdWithBrand(id.Value); //para associar a brand ao veiculo

            if (vehicle == null)
            {
                return NotFound();
            }

            var vmodel = _converterHelper.ToVehicleViewModel(vehicle);  // o objecto vehicle vem sem brand 
            vmodel.Brands = _brandRepository.GetComboBrands();
            vmodel.BrandId = vehicle.Brand.Id;

            return View(vmodel);
        }



        // POST: Vehicles/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(VehicleViewModel vmodel)   //tive um problema de nomes em que não me passava o viewmodel com o nome model (lmao)
        {                                                                //consigo passar o viewmodel mas só vem com o BrandId da ViewModel pois é o que está no hidden="Id"
            if (ModelState.IsValid)
            {
                try
                {
                    var path = string.Empty;

                    var vehicle = _converterHelper.ToVehicle(vmodel, path, false);

                    await _vehicleRepository.UpdateAsync(vehicle);
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!await _vehicleRepository.ExistAsync(vmodel.Id))
                    {
                        return new NotFoundViewResult("VehicleNotFound");
                    }
                    else
                    {
                        throw;
                    }
                }

                if (User.IsInRole("Client"))
                {
                    return RedirectToAction("MyVehicles", "Clients");
                }
                return RedirectToAction(nameof(Index));
            }
            return View(vmodel);
        }




        // GET: Vehicles/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new NotFoundViewResult("VehicleNotFound");
            }

            var vehicle = await _vehicleRepository.GetByIdAsync(id.Value);
            if (vehicle == null)
            {
                return new NotFoundViewResult("VehicleNotFound");
            }

            return View(vehicle);
        }



        // POST: Vehicles/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var vehicle = await _vehicleRepository.GetByIdAsync(id);
            await _vehicleRepository.DeleteAsync(vehicle);

            if (User.IsInRole("Client"))
            {
                return RedirectToAction("MyVehicles", "Clients");
            }
            return RedirectToAction(nameof(Index));
        }



        public IActionResult VehicleNotFound()
        {
            return View();
        }
    }
}

AutoWorkshop.Web/Views/Vehicles/Create.cshtml
@model AutoWorkshop.Web.Models.VehicleViewModel

@{
    ViewData["Title"] = "Create";
}

<h2>Create</h2>

<h4>Vehicle</h4>
<hr />
<div class="container-fluid" >

    <form asp-action="Create" >
        <div class="row">
            <div class="col-1">

            </div>
            <div class="col-4">

                <div asp-validation-summary="ModelOnly" class="text-danger"></div>

                <div class="form-group">
                    <label asp-for="Brand" class="control-label"></label>
                    <select asp-for="BrandId" asp-items="Model.Brands" class="form-control"></select>
                    <span asp-validation-for="BrandId" class="text-danger"></span>
                </div>

                <div class="form-group">
                    <label asp-for="Model" class="control-label"></label>
                    <input asp-for="Model" class="form-control" />
                    <span asp-validation-for="Model" class="text-danger"></span>
                </div>

                <div class="form-group">
                    <label asp-for="Type" class="control-label"></label>
                    <input asp-for="Type" class="form-control" />
                    <span asp-validation-for="Type" class="text-danger"></span>
                </div>

                <div class="form-group">
                    <label asp-for="Transmission" class="control-label"></label>
                    <input asp-for="Transmission" class="form-control" />
                    <span asp-validation-for="Transmission" class="text-danger"></span>
                </div>

                <div class="form-group">
                    <label asp-for="Color" class="control-label"></label>
                    <input asp-for="Color" class="form-control" />
                    <span asp-validation-for="Color" class="text-danger"></span>
                </div>

            </div>
            <div class="col-1">

            </div>
            <div class="col-4">

                <div class="form-group">
                    <label asp-for="LastMaintenance" class="control-label"></label>
                    <input asp-for="LastMaintenance" class="form-control" />
                    <span asp-validation-for="LastMaintenance" class="text-danger"></span>
                </div>

                <div class="form-group">
                    <label asp-for="Mileage" class="control-label"></label>
                    <input asp-for="Mileage" class="form-control" />
                    <span asp-validation-for="Mileage" class="text-danger"></span>
                </div>

                <div class="form-group">
                    <label asp-for="EnginePower" class="control-label"></label>
                    <input asp-for="EnginePower" class="form-control" />
                    <span asp-validation-for="EnginePower" class="text-danger"></span>
                </div>

                <div class="form-group">
                    <label asp-for="LicensePlate" class="control-label"></label>
                    <ejs-maskedtextbox id="mask1" ejs-for="LicensePlate" mask=">AA-AA-AA"></ejs-maskedtextbox>
                    @*<input asp-for="LicensePlate" class="form-control" />*@
                    <span asp-validation-for="LicensePlate" class="text-danger"></span>
                </div>

                @if (User.IsInRole("Admin"))
                {
                    <div class="form-group">
                        <label asp-for="Client" class="control-label"></label>
                        <select asp-for="ClientId" asp-items="Model.Clients" class="form-control"></select>
                        <span asp-validation-for="ClientId" class="text-danger"></span>
                    </div>
                }

                <div class="form-group">
                    <button type="submit" class="btn btn-primary btn-block"> Create</button>
                    
                    @if (User.IsInRole("Admin"))
                    {
                        <a asp-action="Index" class="btn btn-dark btn-block">Cancel</a>
                    }
                    else
                    {
                         <a asp-controller="Clients" asp-action="MyVehicles" class="btn btn-dark btn-block">Cancel</a>
                    }
                   
                </div>
            </div>
        </div>
        
    </form>
</div>



@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

AutoWorkshop.Web/Views/Vehicles/Delete.cshtml
@model AutoWorkshop.Web.Data.Entities.Vehicle

@{
    ViewData["Title"] = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Vehicle</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Model)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Model)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Transmission)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Transmission)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Type)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Type)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Color)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Color)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Mileage)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Mileage)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.EnginePower)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.EnginePower)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.LicensePlate)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.LicensePlate)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.LastMaintenance)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.LastMaintenance)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-default" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

AutoWorkshop.Web/Views/Vehicles/Details.cshtml
@model AutoWorkshop.Web.Data.Entities.Vehicle

@{
    ViewData["Title"] = "Details";
}

<h2>Details</h2>

<div>
    <h4>Vehicle</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Brand.BrandName)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Brand.BrandName)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Model)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Model)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Transmission)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Transmission)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Type)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Type)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Color)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Color)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Mileage)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Mileage)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.EnginePower)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.EnginePower)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.LicensePlate)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.LicensePlate)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.LastMaintenance)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.LastMaintenance)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

AutoWorkshop.Web/Views/Vehicles/Edit.cshtml
@model AutoWorkshop.Web.Models.VehicleViewModel

@{
    ViewData["Title"] = "Edit";
}

<h2>Edit</h2>

<h4>Vehicle</h4>
<hr />
<div class="container-fluid">

    <form method="post">
        <div class="row">
            <div class="col-1">

            </div>
            <div class="col-4">

                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <input type="hidden" asp-for="Id" />
                <input type="hidden" asp-for="ClientId" />


                <div class="form-group">
                    <label asp-for="Brand" class="control-label"></label>
                    <select asp-for="BrandId" asp-items="Model.Brands" class="form-control"></select>
                    <span asp-validation-for="BrandId" class="text-danger"></span>
                </div>

                <div class="form-group">
                    <label asp-for="Model" class="control-label"></label>
                    <input asp-for="Model" class="form-control" />
                    <span asp-validation-for="Model" class="text-danger"></span>
                </div>

                <div class="form-group">
                    <label asp-for="Type" class="control-label"></label>
                    <input asp-for="Type" class="form-control" />
                    <span asp-validation-for="Type" class="text-danger"></span>
                </div>

                <div class="form-group">
                    <label asp-for="Transmission" class="control-label"></label>
                    <input asp-for="Transmission" class="form-control" />
                    <span asp-validation-for="Transmission" class="text-danger"></span>
                </div>

                <div class="form-group">
                    <label asp-for="Color" class="control-label"></label>
                    <input asp-for="Color" class="form-control" />
                    <span asp-validation-for="Color" class="text-danger"></span>
                </div>

            </div>
            <div class="col-1">

            </div>
            <div class="col-4">

                <div class="form-group">
                    <label asp-for="LastMaintenance" class="control-label"></label>
                    <input asp-for="LastMaintenance" class="form-control" />
                    <span asp-validation-for="LastMaintenance" class="text-danger"></span>
                </div>

                <div class="form-group">
                    <label asp-for="Mileage" class="control-label"></label>
                    <input asp-for="Mileage" class="form-control" />
                    <span asp-validation-for="Mileage" class="text-danger"></span>
                </div>

                <div class="form-group">
                    <label asp-for="EnginePower" class="control-label"></label>
                    <input asp-for="EnginePower" class="form-control" />
                    <span asp-validation-for="EnginePower" class="text-danger"></span>
                </div>

                <div class="form-group">
                    <label asp-for="LicensePlate" class="control-label"></label>
                    <input asp-for="LicensePlate" class="form-control" />
                    <span asp-validation-for="LicensePlate" class="text-danger"></span>
                </div>

                <div class="form-group">
                    <button type="submit" class="btn btn-primary btn-block">Save Changes</button>

                    @if (User.IsInRole("Admin"))
                    {
                        <a asp-action="Index" class="btn btn-dark btn-block">Cancel</a>
                    }
                    else
                    {
                         <a asp-controller="Clients" asp-action="MyVehicles" class="btn btn-dark btn-block">Cancel</a>
                    }

                </div>
            </div>
        </div>       
    </form>
</div>


@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

AutoWorkshop.Web/Views/Vehicles/Index.cshtml
@model IEnumerable<AutoWorkshop.Web.Data.Entities.Vehicle>

@{
    ViewData["Title"] = "Index";
}
<br />
<h2>Vehicles</h2>

<div id="testedetails"></div>
<br />

<div>
    <a asp-action="Create" class="btn btn-block" style="background-color: darkorange; font-size: small; color:white">Create New Vehicle</a>
</div>

<br />
<br />

<div class="container body-content">
    <div class="page-header">
        <div class="form-group">
            <fieldset>
                <form action="" class="form-group" method="post">
                    <div class="table-responsive">
                        <div class="table-responsive">
                            <table id="vehicle" class="table table-striped table-bordered table-hover" cellspacing="0" width="100%">
                                <thead class="thead-dark">
                                    <tr>
                                        <th>
                                            @Html.DisplayNameFor(model => model.Brand.BrandName)
                                        </th>
                                        <th>
                                            @Html.DisplayNameFor(model => model.Model)
                                        </th>
                                        <th>
                                            @Html.DisplayNameFor(model => model.Mileage)
                                        </th>
                                        <th>
                                            @Html.DisplayNameFor(model => model.LicensePlate)
                                        </th>
                                        <th>
                                            @Html.DisplayNameFor(model => model.LastMaintenance)
                                        </th>
                                        <th>
                                            @Html.DisplayNameFor(model => model.Client)
                                        </th>
                                        <th>
                                            @Html.DisplayNameFor(model => model.Client.PhoneNumber)
                                        </th>
                                        <th></th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach (var item in Model)
                                    {
                                        <tr>
                                            <td onclick="details(@item.Id)">
                                                @Html.DisplayFor(modelItem => item.Brand.BrandName)
                                            </td>
                                            <td onclick="details(@item.Id)">
                                                @Html.DisplayFor(modelItem => item.Model)
                                            </td>
                                            <td onclick="details(@item.Id)">
                                                @Html.DisplayFor(modelItem => item.Mileage)
                                            </td>
                                            <td onclick="details(@item.Id)">
                                                @Html.DisplayFor(modelItem => item.LicensePlate)
                                            </td>
                                            <td onclick="details(@item.Id)">
                                                @Html.DisplayFor(modelItem => item.LastMaintenance)
                                            </td>
                                            <td onclick="details(@item.Id)">
                                                @Html.DisplayFor(modelItem => item.Client.FullName)
                                            </td>
                                             <td onclick="details(@item.Id)">
                                                @Html.DisplayFor(modelItem => item.Client.PhoneNumber)
                                            </td>
                                            <td >
                                                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                                                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
                                            </td>
                                        </tr>
                                    }
                                </tbody>
                            </table>
                        </div>
                    </div>
                </form>            
            </fieldset>
        </div>
        <hr />
    </div>
</div>

<br />
<br />








<script type="text/javascript">

    function details(id) {
         $.ajax({
             url: "@Url.Action("GetVehicles", "Vehicles")",
             type: 'GET',
             data: { Id: id },
             contentType: false,
             success: function (res) {
                 var PlaceHolder = $("#testedetails");

                 PlaceHolder.html(res);
                 PlaceHolder.find('.modal').modal('show');
             }
         })
    }

    $(document).ready(function () {
        $('#vehicle').DataTable();
    });


    //$(function () {
    //    var PlaceHolder = $("#PlaceHolder");
    //    $('table tbody tr').on('click', function (event) {

    //        event.preventDefault();
    //        event.stopImmediatePropagation();

    //        var url = $(this).data('url');
    //        var decodedUrl = decodeURIComponent(url);

    //        $.get(decodedUrl).done(function (data) {
    //            PlaceHolder.html(data);
    //            PlaceHolder.find('.modal').modal('show');

    //            return;
    //        })
    //    })
    //})
</script>

AutoWorkshop.Web/Views/Vehicles/VehicleNotFound.cshtml
@{
    ViewData["Title"] = "Vehicle Not Found";
}

<h2>VEHICLE NOT FOUND!</h2>

AutoWorkshop.Web/Views/Vehicles/_VehiclesPartial.cshtml
@model AutoWorkshop.Web.Data.Entities.Vehicle


<div class="modal fade" id="vehicleModal">
    <div class="modal-dialog modal-lg modal-dialog-centered">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title float-left">Details</h4>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            </div>
            <div class="modal-body">
                <div style="background-color:darkorange; display: block; height: 6px;margin-bottom: 10px;"></div>
                <div class="container">
                    <div class="row" style="font-size: 16px">
                        <div class="col-2 font-weight-bold text-dark">
                            <p><span>Brand: </span></p>
                            <p><span>Model: </span></p>
                            <p><span>Type: </span></p>
                            <p><span>Transmission: </span></p>
                            <p><span>Color: </span></p>
                        </div>
                        <div class="col-4">
                            <p>@Model.Brand.BrandName</p>
                            <p>@Model.Model</p>
                            <p>@Model.Type</p>
                            <p>@Model.Transmission</p>
                            <p>@Model.Color</p>
                        </div>

                        <div class="col-3 font-weight-bold">
                            <br />
                            <p><span class="text-dark">Engine Power:</span></p>
                            <p><span class="text-dark">Mileage:</span></p>
                            <p><span class="text-dark">License Plate:</span></p>
                            <p><span class="text-dark">Last Maintenance:</span></p>
                        </div>
                        <div class="col-3">
                            <br />
                            <p>@Model.EnginePower  cv</p>
                            <p>@Model.Mileage  km</p>
                            <p>@Model.LicensePlate</p>
                            <p>@Model.LastMaintenance.Value.ToShortDateString()</p>
                        </div>
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                @*<button type="button" class="btn btn-default" data-dismiss="modal">Close</button>*@
            </div>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div><!-- /.modal -->